name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    name: Heroku Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "multicubing"
          heroku_email: "ukasz.klimkiewicz@gmail.com"
